---

- name: Add the user 'postgres'
  user:
    name: postgres

- name: Install PosrgreSQL wget
  yum: name=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm state=present

- name: Install PostgreSQL
  yum: name={{ item }} state=latest
  with_items:
    - postgresql12
    - postgresql12-server
    - postgresql12-contrib

- name: Install cluster PostgreSQL
  command: /usr/pgsql-12/bin/initdb -D /var/lib/pgsql/12/data/ 
  become: true
  become_user: postgres

- name: Change startup config postgresql-12.service
  lineinfile: 
    path: /lib/systemd/system/postgresql-12.service
    regexp: '^Environment=PGDATA='
    line: 'Environment=PGDATA=/var/lib/pgsql/12/data/'

- name: Add PGDATA variable in profile postgres user
  lineinfile:
    path: /home/postgres/.bashrc
    line: 'export PATH=/usr/pgsql-12/bin:\$PATH'

- name: Add PGDATA variable in profile postgres user
  lineinfile:
    path: /home/postgres/.bashrc
    regexp: '^export PATH'
    line: 'PATH=$PATH:/usr/pgsql-12/bin/'

- name: Add PGDATA variable in profile postgres user
  lineinfile:
    path: /home/postgres/.bashrc
    line: 'export PGDATA=/var/lib/pgsql/12/data'    

- name: Change shared_buffer
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    regexp: '^shared_buffers'
    line: 'shared_buffers= {{ shared_buffers }}'

- name: Change work_mem
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    regexp: '^work_mem'
    line: 'work_mem= {{ work_mem }}'

- name: Change effective_cache_size
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    regexp: '^effective_cache_size'
    line: 'effective_cache_size= {{ effective_cache_size }}'

- name: Change listen_addresses
  lineinfile:
    path: /var/lib/pgsql/12/data/postgresql.conf
    line: "listen_addresses='*'"

- name: add allow md5 to pg_hba.conf
  lineinfile:
    path: /var/lib/pgsql/12/data/pg_hba.conf
    line: 'host all all 10.1.200.10/24 trust'

- name: Start PostgreSQL and Enable as service
  service: name=postgresql-12.service state=started enabled=yes

- name: open firewall
  shell: firewall-cmd --permanent --add-port=5432/tcp

- name: reload firewall
  shell: firewall-cmd --reload

  yum install redhat-rpm-config
  dnf install postgresql12-devel
  /usr/pgsql-12/lib/pgxs/src/makefiles
  cp -R  /usr/pgsql-12/lib/pgxs/ /usr/lib64/pgsql/
  /usr/lib64/pgsql/pgxs/src/makefiles/

  cp -R /usr/pgsql-12/include /usr/lib64/pgsql/lib/include
  cp -R /usr/pgsql-12/include/server/ /usr/include