---

  # - name: change hostname

  # - name: Copy a new sudoers file into place, after passing validation with visudo
  #   template:
  #    src: hosts.j2
  #    dest: /etc/hosts
  #    force: yes

  - name: Change the hostname to our standard
    hostname: name="{{ inventory_hostname }}"
    when: ansible_fqdn != ansible_ssh_host

  - name: great a new disk
    command: pvcreate /dev/sdb

  - name: extend existing vg
    command: vgextend centos /dev/sdb

  - name: extend existing LVM
    command: lvextend /dev/centos/root -l +100%FREE

  - name: Resize filesystem
    command: xfs_growfs /dev/centos/root