version: '2'
services:
    pgbouncer:
        image: mbed/pgbouncer
        build: .
        environment:
          PG_PORT_5432_TCP_ADDR: postgres
          PG_PORT_5432_TCP_PORT: 5432
          PG_ENV_POSTGRESQL_USER: root
          PG_ENV_POSTGRESQL_PASS: suchsecuremanypassword
        links:
          - postgres



          docker run --rm \
           DB_USER=user 
           DB_PASSWORD=pass 
           DB_HOST=postgres-host 
           DB_NAME=database 
          -v pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
          -p 5432:5432
          edoburu/pgbouncer
      
version: '2'
services:
    pgbouncer:
        image: edoburu/pgbouncer
        build: .
        environment:
            DB_USER=postgres 
            DB_PASSWORD=Vfhnvfhn123 
            DB_HOST=10.1.200.11 
            DB_NAME=postgres 
        version: '3.5'

    volumes:
        - pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini



