---

- name: Install PostgreSQL patroni
  hosts: barmans
  become: yes


  roles:
    #  - equipping
    #  - etcd
    #  - postgresql
    #  - haproxy
    #  - keepalived
    #  - barman_client
     - barman_server
    #  - postgresql_standalone
    #  - pci_dss