# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---

- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: mp-admin
    env_password: wvN9cZSo5ww
    env_host: https://vcd.sbercloud.ru/
    env_org: FNFRO
    env_api_version: 30.0
    env_verify_ssl_certs: true
  roles:
    #  - del_vappvm
     - vappvm_loop