---

global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/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

route: 
  receiver: devops_alert
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m
  group_by: ['alertname']

receivers:
  - name: devops_alert
    slack_configs:
    - channel: '#general'
      icon_url: 'https://www.flaticon.com/premium-icon/icons/svg/2550/2550663.svg'
      send_resolved: true
      