alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']

global: 
  evaluation_interval: 15s
  scrape_interval: 15s

rule_files: 
  - alert.rules.yml

scrape_configs: 
  - 
    job_name: node-exporter_postgres
    static_configs: 
      - 
        targets: 
          - "10.1.200.12:9100"
          - "10.1.200.11:9100"
  - 
    job_name: prechkalov_postgres_exporter
    static_configs: 
      - 
        targets: 
          - "10.1.200.15:9187"
          - "10.1.200.16:9187"
          - "10.1.200.17:9187"
  - 
    job_name: prechkalov_node_exporter
    static_configs: 
      - 
        targets: 
          - "10.1.200.15:9100"
          - "10.1.200.16:9100"
          - "10.1.200.17:9100"
  - 
    job_name: postgres-exporter
    static_configs: 
      - 
        targets: 
          - "10.1.200.12:9187"
          - "10.1.200.11:9187"
  - 
    job_name: node-exporter_swarm
    static_configs: 
      - 
        targets: 
          - "v0.mng.i.sw-d.prosvet.tech:9100"
          - "v1.mng.i.sw-d.prosvet.tech:9100"
          - "v2.mng.i.sw-d.prosvet.tech:9100"
          - "v0.wrk.i.sw-d.prosvet.tech:9100"
          - "v1.wrk.i.sw-d.prosvet.tech:9100"
  - 
    job_name: cadvisor_swarm
    static_configs: 
      - 
        targets: 
          - "v0.mng.i.sw-d.prosvet.tech:9300"
          - "v1.mng.i.sw-d.prosvet.tech:9300"
          - "v2.mng.i.sw-d.prosvet.tech:9300"
          - "v0.wrk.i.sw-d.prosvet.tech:9300"
          - "v1.wrk.i.sw-d.prosvet.tech:9300"
  - 
    job_name: docker_swarm
    static_configs: 
      - 
        targets: 
          - "v0.mng.i.sw-d.prosvet.tech:9323"
          - "v1.mng.i.sw-d.prosvet.tech:9323"
          - "v2.mng.i.sw-d.prosvet.tech:9323"
          - "v0.wrk.i.sw-d.prosvet.tech:9323"
          - "v1.wrk.i.sw-d.prosvet.tech:9323"
  - 
    job_name: consul
    static_configs: 
      - 
        targets: 
          - "e.consul.prechkalov.2.stand.prosvet.tech:80"
  - 
    job_name: "metrics traefik"
    static_configs: 
      - 
        targets: 
          - "v0.mng.i.sw-d.prosvet.tech:9400"
          - "v1.mng.i.sw-d.prosvet.tech:9400"
          - "v2.mng.i.sw-d.prosvet.tech:9400"
  - 
    dns_sd_configs: 
      - 
        names: 
          - tasks.cadvisor
        port: 8080
        type: A
    job_name: cadvisor
    scrape_interval: 5s
  - 
    dns_sd_configs: 
      - 
        names: 
          - tasks.node-exporter
        port: 9100
        type: A
    job_name: node-exporter
    scrape_interval: 5s
