---
- name: Lynis | add repo
  copy:
    src: lynis.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: '0644'   

- name: Lynis | install
  yum:
    name: lynis
    update_cache: yes
    state: latest

- name: Lynis | pentest
  shell:
    cmd: lynis --pentest

- name: Lynis | report suggestions
  shell: "grep 'suggestion' {{ lynis_report }}"
  register: grep_output
  ignore_errors: true

- debug:
    var: grep_output.stdout_lines
  when: grep_output.stdout != ""  

- name: Install epel-release
  yum: name=epel-release state=latest

- name: Install  python
  yum: name=python-pip state=latest

- name: install python packages
  pip: name=pymongo

- name: Configure the package management system
  template: src=mongodb-org-4.2.repo.j2 dest=/etc/yum.repos.d/mongodb-org-4.2.repo backup=yes

- name: install mongodb
  yum: name=mongodb-org state=latest

# - name: Disable SELinux
#   selinux:
#     state: disabled

# - name: Configure the package management system with replica
#   template: src=mongod.conf1.j2 dest=/etc/mongod.conf backup=yes

# - name: start service mongod
#   service: 
#    name: mongod.service
#    state: started

# - name: add usr
#   mongodb_user:
#     database: admin
#     name: useradmin
#     roles: userAdminAnyDatabase
#     password: 12345DB
#     state: present
  
- name: Configure key
  template:
    src: keyfile.j2 
    dest: /var/lib/mongo/keyfile 
    backup: yes
    owner: mongod
    group: mongod
    mode: 0600

- name: Configure the package management system with replica
  template: src=mongod.conf.j2 dest=/etc/mongod.conf backup=yes force=yes  

- name: start service mongod
  service: 
   name: mongod.service
   state: started

- name: open firewall 27017
  shell: firewall-cmd --permanent --add-port={{item}}/tcp
  with_items:
   - 27017

- name: reload firewall
  shell: firewall-cmd --reload
