version: '3'

services:

  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --configsvr --replSet configsvr --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1:/data/db
    restart: unless-stopped

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --replSet configsvr --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2:/data/db
    restart: unless-stopped

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo
    command: mongod --configsvr --replSet configsvr --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3:/data/db
    restart: unless-stopped

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  cfgsvr3: {}
 